// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hpvpueptlyyatzwkouxd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhwdnB1ZXB0bHl5YXR6d2tvdXhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkzNzA4MDEsImV4cCI6MjA1NDk0NjgwMX0.YmVLB8UCh16Ksf4p3-p9o3_hkK4d51Pf90g2tgLEPlc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);